SET 'auto.offset.reset' = 'earliest';

-- Create RAW table
CREATE TABLE TBL_WEATHER_ALERT_APP_0010_RAW (ROWKEY INT PRIMARY KEY)
	WITH (
			KAFKA_TOPIC = 'weather.alert.app.source',
			VALUE_FORMAT = 'AVRO'
			);

-- Filter rainy days 
CREATE TABLE TBL_WEATHER_ALERT_APP_0020_RAIN_IS_HERE AS

SELECT ROWKEY,
	CURRENT -> DT AS CURRENT_DT_TIME,
	CURRENT -> TEMP AS CURRENT_TEMP,
	CURRENT -> WEATHER [1] -> DESCRIPTION AS CURRENT_WEATHER_DESC
FROM TBL_WEATHER_ALERT_APP_0010_RAW
WHERE UCASE(CURRENT -> WEATHER [1] -> DESCRIPTION) LIKE '%RAIN%' EMIT CHANGES;

